name: build

on:
  push:
    branches:
      - main
      - new-rayinstall
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux]
        goarch: [amd64, arm, arm64, 386]
        exclude:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build rays
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd rays
          go build -o rays
          
          # Copy rays binary to rayinstall directory
          cp rays ../rayinstall/
          
          # Create version
          RAY_VERSION=$(cat version)
          echo "$RAY_VERSION" > ../rayinstall/version
          
      - name: Build rayinstall for target platform
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd rayinstall
          OUTPUT_NAME="rayinstall-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "$GOOS" = "windows" ]; then
            OUTPUT_NAME+=".exe"
          fi
          go build -o $OUTPUT_NAME .
          
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          path: rayinstall/rayinstall-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
